twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # the value is the service's id
        form_helper: '@App\Helpers\FormularioDinamicoHelper'
        form_repository: '@App\Repository\FormularioRepository'
        voter_helper: '@App\Helpers\VoterHelper'