vich_uploader:
    db_driver: orm

    mappings:
        aluno_image:
            uri_prefix: /images/alunos
            upload_destination: '%kernel.project_dir%/public/images/alunos'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
