<?php

namespace App\Controller;

use App\Entity\Comentario;
use App\Entity\EntityInterface;
use App\Form\ComentarioType;
use App\Helpers\TemplateManager;
use App\Repository\AlunoRepository;
use App\Repository\ComentarioRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/comentario")
 */
class ComentarioController extends AbstractAppController
{
    protected $aluno;

    public function __construct(ComentarioRepository $entityRepository, SessionInterface $session, AlunoRepository $alunoRepository)
    {
        $this->entity = new Comentario();
        $this->entityRepository = $entityRepository;
        $this->entityName = 'comentario';
        $this->entityDisplayedName = 'Fotos/Vídeos';
        $this->formType = ComentarioType::class;

        if (null !== $session->get('aluno_id')) {
            $this->aluno = $alunoRepository->find($session->get('aluno_id'));
        }
    }

    /**
     * @Route("/{page}/page", name="comentario_index", methods="GET|POST", defaults={"page" = 1})
     * @IsGranted("comentario_list")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        return parent::index($paginator, $request);
    }

    /**
     * @Route("/new", name="comentario_new", methods="GET|POST")
     * @IsGranted("comentario_new")
     */
    public function new(Request $request, UserInterface $user): Response
    {
        $form = $this->createForm($this->formType, $this->entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entity->setUsuario($user);

            $this->entity->setAluno($this->aluno);

            $em = $this->getDoctrine()->getManager();
            $em->persist($this->entity);
            $em->flush();

            //return $this->redirectToRoute("{$this->entityName}_index");
            return $this->redirectToRoute('perfil_aluno_profile', [
                'id' => $this->aluno->getId(),
            ]);
        }

        return $this->render($this->getTemplateManager()->getNew(), [
            'form' => $form->createView(),
            'entityName' => $this->entityName,
            'entityDisplayedName' => $this->entityDisplayedName,
            'template' => (array) $this->getTemplateManager(),
        ]);
    }

    /**
     * @Route("/{id}", name="comentario_show", methods="GET")
     * @ParamConverter("entity", class="App\Entity\Comentario")
     * @IsGranted("comentario_show", subject="entity")
     */
    public function show(EntityInterface $entity): Response
    {
        return parent::show($entity);
    }

    /**
     * @Route("/{id}/edit", name="comentario_edit", methods="GET|POST")
     * @ParamConverter("entity", class="App\Entity\Comentario")
     * @IsGranted("comentario_edit", subject="entity")
     */
    public function edit(Request $request, EntityInterface $entity): Response
    {
        return parent::edit($request, $entity);
    }

    /**
     * @Route("/{id}", name="comentario_delete", methods="DELETE")
     * @ParamConverter("entity", class="App\Entity\Comentario")
     * @IsGranted("comentario_delete", subject="entity")
     */
    public function delete(Request $request, EntityInterface $entity): Response
    {
        return parent::delete($request, $entity);
    }

    protected function getForm(EntityInterface $entity)
    {
        $form = parent::getForm($entity); // TODO: Change the autogenerated stub
        $form->remove('file');

        return $form;
    }

    protected function getTemplateManager(): TemplateManager
    {
        $templateManager = parent::getTemplateManager();
        $templateManager->setForm('comentario/_form.html.twig');

        return $templateManager;
    }
}
